generator {
  seed = 42
  profile = "small"
  cardinality-profile = "medium"
  scenario = "baseline"
}

output {
  directory = "data/raw"
}

distributions {

  order_status {
    type = "weighted"

    values {
      PLACED = 0.05
      CONFIRMED = 0.15
      SHIPPED = 0.15
      DELIVERED = 0.60
      CANCELLED = 0.05
    }
  }

  payment_method {
    type = "weighted"

    values {
      UPI = 0.45
      CREDIT_CARD = 0.20
      DEBIT_CARD = 0.15
      NET_BANKING = 0.10
      WALLET = 0.10
    }
  }

  device_type {
    type = "weighted"

    values {
      MOBILE = 0.70
      DESKTOP = 0.25
      TABLET = 0.05
    }
  }

  channel {
    type = "weighted"

    values {
      ORGANIC = 0.35
      PAID_SEARCH = 0.20
      SOCIAL = 0.15
      EMAIL = 0.10
      DIRECT = 0.15
      REFERRAL = 0.05
    }
  }
}

product-pricing {

  CATEGORY_001 {
    min = 500.0
    max = 150000.0
    mode = 30000.0
  }

  CATEGORY_002 {
    min = 3000.0
    max = 150000.0
    mode = 30000.0
  }

  CATEGORY_003 {
    min = 25000.0
    max = 250000.0
    mode = 60000.0
  }

  CATEGORY_004 {
    min = 8000.0
    max = 250000.0
    mode = 40000.0
  }

  CATEGORY_005 {
    min = 500.0
    max = 150000.0
    mode = 20000.0
  }

  CATEGORY_006 {
    min = 200.0
    max = 25000.0
    mode = 1500.0
  }

  CATEGORY_007 {
    min = 300.0
    max = 30000.0
    mode = 2500.0
  }

  CATEGORY_008 {
    min = 100.0
    max = 15000.0
    mode = 1000.0
  }

  CATEGORY_009 {
    min = 100.0
    max = 5000.0
    mode = 500.0
  }

  CATEGORY_010 {
    min = 20.0
    max = 5000.0
    mode = 300.0
  }
}